on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

  workflow_dispatch:

jobs:
  Dev:
    runs-on: ubuntu-latest
    environment: Dev
    
    steps:
      - uses: actions/checkout@v2
      - name: Run a script ${{secrets.MY_SECRET}}
        run: |
          echo "running job in Dev env"
      
