name: "Upload on S3"
on:
  # Manual trigger
  workflow_dispatch:
  push:
    paths:
      - 'simple/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'simple/**'
defaults:
  run:
    shell: bash
    working-directory: simple
jobs:
  s3-upload:
    name:   ${{matrix.runner}} - ${{ matrix.environment }}
    runs-on: [ '${{ matrix.runner }}']
    strategy:
      max-parallel: 1
      matrix:
         include:
           - environment: test
             runner: ubuntu-latest
           - environment: prod
             runner: ubuntu-18.04
    env:
         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
         AWS_DEFAULT_REGION: us-east-2
    steps:
      - uses: actions/checkout@v2
      - name: Copy files to the test website with the AWS CLI
        run: echo Hello, world!
      - name: Run only if push to main branch
        if: github.ref == 'refs/heads/main'
        id: apply
        run: echo Run only when push to main branch
